<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxsbq34\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWxsbq34/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWxsbq34.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWxsbq34\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWxsbq34\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wxsbq34',
    'container.build_id' => '74a9c622',
    'container.build_time' => 1695150920,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWxsbq34');
