controllers:
    resource: ../src/Controller/
    type: attribute



login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: [GET]


inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::showForm
